name: Create Prerelease on Merge

on:
  pull_request:
    types: [closed]
    branches:
      - main

env:
  BRANCH_NAME: ${{ github.ref_name }}

jobs:
  create_prerelease:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: update version
        run: |
          npm version prerelease --no-git-tag-version --preid=$BRANCH_NAME
          git config --global user.name 'Andrii Oriekhov'
          git config --global user.email 'andriyorehov@gmail.com'
          git add .
          git commit -m "bump version to $(npm pkg get version | tr -d '"')"
          git push
        
