name: Create Prerelease on Merge

on:
  pull_request:
    types: [closed]
    branches:
      - main

jobs:
  create_prerelease:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: update version
        run: |
          npm version prerelease --no-git-tag-version
          git add .
          git commit -m 'bump version'
          git push
        
